composer.json, composer.lock, conf/cmi/core.entity_form_display.media.video.default.yml, conf/cmi/core.entity_form_display.media.video.media_library.yml, conf/cmi/core.entity_view_display.media.video.default.yml, conf/cmi/core.entity_view_display.media.video.media_library.yml, conf/cmi/core.extension.yml, conf/cmi/field.field.media.video.field_media_oembed_video.yml, conf/cmi/field.storage.media.field_media_oembed_video.yml, conf/cmi/language.content_settings.media.video.yml, conf/cmi/language.types.yml, conf/cmi/language/fi/system.menu.main.yml, conf/cmi/media.type.video.yml, public/themes/custom/suomidigi/src/scss/components/misc/_video-wrapper.scss, public/themes/custom/suomidigi/templates/field/field--media--field-media-oembed-video--video.html.twig
2. Go check that there is a new media type: Video
3. Go to http://suomidigi.fi.docker.amazee.io/en/media/add/video and add a remote video
4. Add a media field to e.g. basic page content type
5. Add a new basic page node and add your remote video by clicking on the add media button
6. Check that the video looks good and is responsive
=> SUOPA-152: Video media type with external video

conf/cmi/block.block.suopa_shortcuts_block_mobile.yml, conf/cmi/block.block.suopa_shortcuts_block_sidebar.yml, conf/cmi/language/fi/views.view.suopa_shortcuts.yml, conf/cmi/views.view.suopa_shortcuts.yml, public/themes/custom/suomidigi/src/js/menu.mobile.js, public/themes/custom/suomidigi/src/scss/components/navigation/_menu-mobile.scss, public/themes/custom/suomidigi/src/scss/components/navigation/_menu-sidebar.scss, public/themes/custom/suomidigi/src/scss/components/navigation/_shortcuts.scss, public/themes/custom/suomidigi/suomidigi.theme, public/themes/custom/suomidigi/templates/blocks/block--views-block--suopa-shortcuts-block.html.twig, public/themes/custom/suomidigi/templates/content/taxonomy-term--theme--teaser.html.twig
2. Go to http://suomidigi.fi.docker.amazee.io/ on desktop width and check that there's shortcuts on the sidebar. Switch to mobile width and check that there's the same shortcuts underneath mobile navigation links
3. Go to http://suomidigi.fi.docker.amazee.io/en/ and make sure the shortcut links differ from the Finnish ones
=> SUOPA-149 Shortcuts

composer.json, composer.lock, conf/cmi/core.entity_form_display.media.icon.default.yml, conf/cmi/core.entity_form_display.media.icon.media_library.yml, conf/cmi/core.entity_view_display.media.icon.default.yml, conf/cmi/core.entity_view_display.media.icon.media_library.yml, conf/cmi/core.entity_view_display.media.icon.media_paragraph.yml, conf/cmi/core.extension.yml, conf/cmi/entity_browser.browser.media_browser.yml, conf/cmi/entity_browser.browser.media_icon_browser.yml, conf/cmi/field.field.media.icon.field_media_image.yml, conf/cmi/field.field.paragraph.media.field_p_media.yml, conf/cmi/language.content_settings.media.icon.yml, conf/cmi/media.type.icon.yml, conf/cmi/views.view.media_entity_browser.yml, public/modules/custom/suopa_editorial/composer.json, public/modules/custom/suopa_editorial/drush.services.yml, public/modules/custom/suopa_editorial/src/Commands/GenerateIconMediaEntities.php
To test: 
- `make fresh`
- `make shell`
- Run drush command `drush gemi /themes/custom/suomidigi/icons/svg`
- Go to http://suomidigi.fi.docker.amazee.io/admin/content/media and check that the programmatically created icons exist
- Try to add some icons to various places and see that all is a-okay.
=> SUOPA-155 Media management

composer.json, composer.lock, conf/cmi/core.extension.yml, conf/cmi/language/en/system.menu.main.yml, conf/cmi/language/fi/views.view.scheduler_scheduled_content.yml, conf/cmi/node.type.article.yml, conf/cmi/node.type.page.yml, conf/cmi/scheduler.settings.yml, conf/cmi/views.view.scheduler_scheduled_content.yml
2. Go create an article or a basic page.
3. Set its scheduling time (3 hours backwards, currently drupal timeformat -> 15:00 is 12:00)
4. Run cron when the time is right ...
5. Check that the node is published
=> SUOPA-200: Content Scheduling

conf/cmi/core.entity_form_display.paragraph.container.default.yml, conf/cmi/core.entity_view_display.paragraph.container.default.yml, conf/cmi/field.field.paragraph.container.field_p_content_50_50.yml, conf/cmi/field.field.paragraph.container.field_p_reverse.yml, conf/cmi/field.field.paragraph.container.field_p_small_image.yml, conf/cmi/field.storage.paragraph.field_p_content_50_50.yml, public/themes/custom/suomidigi/src/scss/components/paragraph/_paragraph--container.scss, public/themes/custom/suomidigi/src/scss/components/paragraph/_paragraph--cta.scss, public/themes/custom/suomidigi/src/scss/library/variables/_colors.scss, public/themes/custom/suomidigi/templates/paragraph/paragraph--container.html.twig, public/themes/custom/suomidigi/templates/paragraph/paragraph--highlight-cta.html.twig
2. Create a node with paragraph possibility.
3. Add `Container 50/50` paragraph items
4. Add content and try to break the layout with different checked checkboxes ...
5. Check that the new checkbox works and the CSS logic doesn't break anything
=> SUOPA-244: Paragraph Container 50/50 - New Checkbox

composer.json, composer.lock, conf/cmi/core.entity_view_display.taxonomy_term.article_type.default.yml, conf/cmi/core.extension.yml, conf/cmi/language.content_settings.redirect.redirect.yml, conf/cmi/language/fi/system.action.redirect_delete_action.yml, conf/cmi/language/fi/views.view.redirect.yml, conf/cmi/redirect.settings.yml, conf/cmi/redirect_404.settings.yml, conf/cmi/system.action.redirect_delete_action.yml, conf/cmi/user.role.content_producer.yml, conf/cmi/views.view.redirect.yml
To test:
- `make fresh`
- Change titles of nodes and theme taxonomy tags and see that the redirects are being created
- It'll work on other paths as well, but no need to test them
- Check the redirect changes from node edit form (there's a new column for the redirects)
- Also check the view: http://suomidigi.fi.docker.amazee.io/admin/config/search/redirect
=> SUOPA-218 Redirect

conf/cmi/views.view.taxonomy_term.yml
To test: 
- `make fresh` or `make drush-cim shell` and `drush cr`
- Go to http://suomidigi.fi.docker.amazee.io/arkkitehtuuri and open a couple of the articles from the bottom of the list to a new tab and edit them
- Tick the "Sticky at top of lists" for each node you opened and save them
- Update the taxonomy term page (arkkitehtuuri) and check that the sorting has been updated
- As a bonus, I added more precise sorting for the nodes. If you tick "Promoted to front page" checkbox on one of the nodes, that'll be on the very top of the list
=> SUOPA-232 Taxonomy term view

public/themes/custom/suomidigi/suomidigi.theme, public/themes/custom/suomidigi/templates/content/node--article--full.html.twig
To test:
- Clear the caches
- Go to f.e. http://suomidigi.fi.docker.amazee.io/palvelut/suomifi-viestit
- Edit the node and change the **Published on** date -> Save node
- Check that the correct date is shown in suomi.fi viestit article
=> SUOPA-265 Article published time

conf/cmi/core.entity_form_display.paragraph.container_title.default.yml, conf/cmi/core.entity_form_display.paragraph.highlight_cta.default.yml, conf/cmi/core.entity_form_display.paragraph.liftup_box_item.default.yml, conf/cmi/core.entity_form_display.paragraph.liftup_prominent.default.yml, conf/cmi/core.entity_form_display.paragraph.link.default.yml, conf/cmi/core.entity_view_display.paragraph.container_title.default.yml, conf/cmi/core.entity_view_display.paragraph.highlight_cta.default.yml, conf/cmi/core.entity_view_display.paragraph.liftup_box_item.default.yml, conf/cmi/core.entity_view_display.paragraph.liftup_prominent.default.yml, conf/cmi/core.entity_view_display.paragraph.link.default.yml, conf/cmi/field.field.paragraph.container_title.field_p_link_target.yml, conf/cmi/field.field.paragraph.container_title.field_p_title.yml, conf/cmi/field.field.paragraph.highlight_cta.field_p_link_target.yml, conf/cmi/field.field.paragraph.liftup_box_item.field_p_link_target.yml, conf/cmi/field.field.paragraph.liftup_prominent.field_p_link_target.yml, conf/cmi/field.field.paragraph.link.field_p_link_target.yml, conf/cmi/field.storage.paragraph.field_p_link_target.yml, public/themes/custom/suomidigi/templates/paragraph/paragraph--container-title.html.twig, public/themes/custom/suomidigi/templates/paragraph/paragraph--highlight-cta.html.twig, public/themes/custom/suomidigi/templates/paragraph/paragraph--liftup-box-item.html.twig, public/themes/custom/suomidigi/templates/paragraph/paragraph--liftup-prominent.html.twig, public/themes/custom/suomidigi/templates/paragraph/paragraph--link.html.twig
2. Links can be found in paragraphs: `Link`, `Container with Title`, `Highlight - CTA`, `Liftup - Box Item` and `Liftup - Prominent`
3. Check that these paragraphs have a new field which is a checkbox (open in new window).
4. Test that it works.
=> SUOPA-359: Possibility to make link open in new window

conf/cmi/field.field.node.article.field_header_image.yml
2. Add new article node
3. You'll notice that the header image field has a image already set, if so it works!
=> SUOPA-255: Add default image to article header

composer.json, composer.lock, conf/cmi/core.extension.yml, public/sites/default/all.settings.php
To test:
- `make fresh`
- On local environment the nav bar has default blackish background. If you want to simulate colour change on local environment, you can change the colour from "public/sites/default/all.settings.php". 
If you're satisfied with the code, just merge this PR and see that the nav bar on dev.suomidigi.fi changes to blueish colour.
=> SUOPA-319 Environment indicator

composer.json, composer.lock, public/sites/default/default.settings.php
Update drupal/core to the latest version, due to security update.
https://www.drupal.org/sa-core-2019-008
=> SUOPA-X: Update drupal/core to version 8.7.5

conf/cmi/core.entity_form_display.paragraph.media.default.yml, conf/cmi/core.entity_view_display.paragraph.media.default.yml, conf/cmi/field.field.paragraph.media.field_p_description.yml, public/themes/custom/suomidigi/src/scss/components/paragraph/_paragraph--media.scss, public/themes/custom/suomidigi/src/scss/layout/_page-footer.scss, public/themes/custom/suomidigi/templates/field/field--paragraph--field-p-description--media.html.twig, public/themes/custom/suomidigi/templates/field/field--paragraph--field-p-media--media.html.twig, public/themes/custom/suomidigi/templates/paragraph/paragraph--media.html.twig
2. Go add 2 paragraphs of type media, 1 without description and 1 with description
3. Check that it looks good
=> SUOPA-256: Add description field for paragraph media

public/themes/custom/suomidigi/package-lock.json, public/themes/custom/suomidigi/src/js/leanLabInterQuest.js, public/themes/custom/suomidigi/suomidigi.libraries.yml
To test:
- `make fresh`
- Go to http://suomidigi.fi.docker.amazee.io and check that the questionnaire appears
=> SUOPA-250 Attached leanlab questionnaire code.

conf/cmi/core.entity_form_display.paragraph.liftup_entity_reference_item.default.yml, conf/cmi/core.entity_view_display.node.legislation_collection_page.teaser.yml, conf/cmi/entity_browser.browser.entity_reference_browser.yml, conf/cmi/field.field.node.legislation_collection_page.field_header_image.yml, conf/cmi/field.field.paragraph.liftup_entity_reference_item.field_p_entity_reference.yml, conf/cmi/language/fi/entity_browser.browser.entity_reference_browser.yml, conf/cmi/language/fi/views.view.entity_reference_browser.yml, conf/cmi/views.view.entity_reference_browser.yml, public/themes/custom/suomidigi/src/scss/components/content/_legislation-collection.scss, public/themes/custom/suomidigi/suomidigi.theme, public/themes/custom/suomidigi/templates/content/node--article--teaser.html.twig, public/themes/custom/suomidigi/templates/content/node--legislation-collection-page--full.html.twig, public/themes/custom/suomidigi/templates/content/node--legislation-collection-page--teaser.html.twig
How to test:
- `make fresh`
- Log in and create a Legislation collection page. 
- Give the node a Title and an Ingress
- Remove the default header image and don't add a new one, leaving the field empty
- Add a paragraph which is of type Liftup - Entity Reference
- Filter the node list by Legislation Collection Page and choose the only node what is visible
- Save the node and check that it looks somewhat like this: https://ixonos.invisionapp.com/share/MDTDCNDE54Z#/378076158_Desktop_Lainsa-a-da-nto-
=> SUOPA-425 Legislation collection page teaser

conf/cmi/block.block.menu_desktop.yml, conf/cmi/block.block.suomidigi_branding.yml, conf/cmi/block.block.tervetuloalohko.yml, conf/cmi/core.entity_form_display.paragraph.liftup_entity_reference_item.default.yml, conf/cmi/core.entity_view_display.node.legislation_collection_page.teaser.yml, conf/cmi/entity_browser.browser.entity_reference_browser.yml, conf/cmi/field.field.node.legislation_card.field_legislation_materials.yml, conf/cmi/field.field.node.legislation_collection_page.field_header_image.yml, conf/cmi/field.field.paragraph.liftup_entity_reference_item.field_p_entity_reference.yml, conf/cmi/language/fi/entity_browser.browser.entity_reference_browser.yml, conf/cmi/language/fi/field.field.node.legislation_card.field_legislation_materials.yml, conf/cmi/language/fi/views.view.entity_reference_browser.yml, conf/cmi/views.view.entity_reference_browser.yml, public/themes/custom/suomidigi/src/js/searchToggle.js, public/themes/custom/suomidigi/src/scss/components/content/_legislation-collection.scss, public/themes/custom/suomidigi/src/scss/components/navigation/_menu-desktop.scss, public/themes/custom/suomidigi/src/scss/layout/_page-announcement.scss, public/themes/custom/suomidigi/suomidigi.info.yml, public/themes/custom/suomidigi/suomidigi.theme, public/themes/custom/suomidigi/templates/blocks/block--search-api-view-form.html.twig, public/themes/custom/suomidigi/templates/content/node--article--teaser.html.twig, public/themes/custom/suomidigi/templates/content/node--legislation-collection-page--full.html.twig, public/themes/custom/suomidigi/templates/content/node--legislation-collection-page--teaser.html.twig, public/themes/custom/suomidigi/templates/layout/page.html.twig
To test: 
- `make fresh`
- Clear caches and go to the front page. 
- Check that there's an announcement which welcomes you to the dev-site and that it works on mobile as well
=> SUOPA-477 Announcement block

conf/cmi/user.role.content_producer.yml, conf/cmi/user.role.editor_in_chief.yml, conf/cmi/webform.webform.asiantuntijatuki_digituki.yml, public/themes/custom/suomidigi/templates/content/node--webform.html.twig
=> Exported permissions and added webform node template.

conf/cmi/core.entity_view_display.node.legislation_card.teaser.yml, conf/cmi/views.view.entity_reference_browser.yml, public/modules/custom/suopa_legislations/suopa_legislations.module, public/themes/custom/suomidigi/src/js/searchToggle.js, public/themes/custom/suomidigi/src/scss/components/content/_legislation-card.scss, public/themes/custom/suomidigi/src/scss/components/content/_legislation-collection.scss, public/themes/custom/suomidigi/src/scss/components/content/_legislation-link.scss, public/themes/custom/suomidigi/src/scss/components/form/_search.scss, public/themes/custom/suomidigi/src/scss/layout/_page.scss, public/themes/custom/suomidigi/templates/blocks/block--search-api-view-form.html.twig, public/themes/custom/suomidigi/templates/content/node--legislation-card--teaser.html.twig, public/themes/custom/suomidigi/templates/layout/page.html.twig
To test: 
- `make fresh`
- Go to f.e. http://suomidigi.fi.docker.amazee.io/ and edit it
- Add a new paragraph "Nostot" and select a legislation card for the liftup
- Save the node and check that the liftup looks okay and the expanding works in desktop and mobile widths
=> SUOPA-442 Legislation card teaser

conf/cmi/core.entity_form_display.community.community.default.yml, conf/cmi/core.entity_view_display.community.community.default.yml, conf/cmi/field.field.community.community.field_approved.yml, conf/cmi/field.storage.community.field_approved.yml, conf/cmi/language/fi/webform.webform.add_new_community.yml, conf/cmi/user.role.editor_in_chief.yml, conf/cmi/views.view.content.yml, conf/cmi/webform.webform.add_new_community.yml, public/modules/custom/suopa_communities/src/Plugin/Validation/Constraint/ApprovalConstraint.php, public/modules/custom/suopa_communities/src/Plugin/Validation/Constraint/ApprovalConstraintValidator.php, public/modules/custom/suopa_communities/src/Plugin/WebformHandler/CommunityWebformHandler.php, public/modules/custom/suopa_communities/suopa_communities.links.menu.yml, public/modules/custom/suopa_communities/suopa_communities.module
TO TEST:
- make fresh
- Go here: http://suomidigi.fi.docker.amazee.io/form/add-new-community
- Fill the form.
- An email is sent on submit. (Check mailhog)
- Go here: http://suomidigi.fi.docker.amazee.io/admin/content/community
- Check that the community is created as unpublished (and unapproved).
- Try to publish the community without the approval. It should fail due to a constraint violation. (Other combinations like FALSE FALSE and TRUE TRUE should work, ofc).
- Check once again that you can access the community listing page as an EIC role and that you can edit/delete/create communities.
=> Suopa 97 community addition form

composer.json, composer.lock, conf/cmi/core.entity_form_display.media.video.default.yml, conf/cmi/core.entity_view_display.media.video.default.yml, conf/cmi/core.extension.yml, conf/cmi/field.field.media.video.field_title.yml, conf/cmi/field.storage.media.field_title.yml, conf/cmi/language/fi/field.field.media.video.field_title.yml, conf/cmi/language/fi/language.entity.sv.yml, conf/cmi/language/sv/language.entity.fi.yml, conf/cmi/language/sv/language.entity.sv.yml, conf/cmi/media.type.video.yml, conf/cmi/views.view.content.yml, public/modules/custom/suopa_dream_broker/assets/js/handleDreamBrokerTitle.js, public/modules/custom/suopa_dream_broker/src/Controller/DreamBrokerOembedController.php, public/modules/custom/suopa_dream_broker/suopa_dream_broker.info.yml, public/modules/custom/suopa_dream_broker/suopa_dream_broker.libraries.yml, public/modules/custom/suopa_dream_broker/suopa_dream_broker.module, public/modules/custom/suopa_dream_broker/suopa_dream_broker.routing.yml, public/modules/custom/suopa_media_embed/suopa_media_embed.module
How to test:
- `make fresh`
- Log in and clear the caches
- Go to f.e. http://suomidigi.fi.docker.amazee.io/node/151/edit
- Add new paragraph Media
- Select "Valitse media" and from modal window "Lisää uusi video"
- Paste this address to the URL field https://dreambroker.com/channel/a5id6vbn/iframe/19h485mh
- Add title for the video (it's for admin use only) and save the media
- Save the node and check that the video has appeared to the page
=> SUOPA-507 Dream Broker Oembed

composer.json, composer.lock, conf/cmi/core.extension.yml, conf/cmi/language/fi/metatag.metatag_defaults.front.yml, conf/cmi/language/fi/metatag.metatag_defaults.global.yml, conf/cmi/language/fi/metatag.metatag_defaults.node.yml, conf/cmi/language/fi/metatag.metatag_defaults.taxonomy_term.yml, conf/cmi/language/fi/metatag.metatag_defaults.user.yml, conf/cmi/language/sv/metatag.metatag_defaults.node.yml, conf/cmi/language/sv/metatag.metatag_defaults.taxonomy_term.yml, conf/cmi/language/sv/metatag.metatag_defaults.user.yml, conf/cmi/metatag.metatag_defaults.403.yml, conf/cmi/metatag.metatag_defaults.404.yml, conf/cmi/metatag.metatag_defaults.front.yml, conf/cmi/metatag.metatag_defaults.global.yml, conf/cmi/metatag.metatag_defaults.node.yml, conf/cmi/metatag.metatag_defaults.node__article.yml, conf/cmi/metatag.metatag_defaults.node__core_content.yml, conf/cmi/metatag.metatag_defaults.node__landing_page.yml, conf/cmi/metatag.metatag_defaults.node__legislation_card.yml, conf/cmi/metatag.metatag_defaults.node__legislation_collection_page.yml, conf/cmi/metatag.metatag_defaults.node__webform.yml, conf/cmi/metatag.metatag_defaults.taxonomy_term.yml, conf/cmi/metatag.metatag_defaults.user.yml, public/themes/custom/suomidigi/src/scss/components/content/_article-teaser.scss
To test:
- `make fresh`
- To ease up the process, you can install chrome extension: https://chrome.google.com/webstore/detail/open-graph-preview/ehaigphokkgebnmdiicabhjhddkaekgh?hl=en
- Go to f.e. http://suomidigi.fi.docker.amazee.io/node/74
- Use the chrome extension to check that the proper OG tags are available or check the page source for <meta> -tags
=> SUOPA-531 Open Graph

conf/cmi/core.entity_form_display.media.image.default.yml, conf/cmi/core.entity_view_display.media.image.article_full_header.yml, conf/cmi/core.entity_view_display.media.image.default.yml, conf/cmi/core.entity_view_display.media.image.legislation_collection_page_full_header.yml, conf/cmi/core.entity_view_display.media.image.media_paragraph.yml, conf/cmi/field.field.media.image.field_creator.yml, conf/cmi/field.storage.media.field_creator.yml, conf/cmi/language/fi/field.field.media.image.field_creator.yml, conf/cmi/language/sv/field.field.media.image.field_creator.yml, conf/cmi/webform.webform.asiantuntijatuki_data_ja_rajapin.yml, public/themes/custom/suomidigi/package-lock.json, public/themes/custom/suomidigi/src/scss/components/content/_media-image.scss, public/themes/custom/suomidigi/templates/content/media--image.html.twig, public/themes/custom/suomidigi/templates/field/field--comment.html.twig, public/themes/custom/suomidigi/templates/field/field--media--field-creator.html.twig
To test:
- `make fresh`
- Go to any article page or http://suomidigi.fi.docker.amazee.io/blogit/tukialy-ensihoitajan-avuksi
- Quick edit the image (see image below) and add your name to Creator field
- Save and see if the creators' name has appeared to the page
=> SUOPA-568 Photo field

composer.json, composer.lock, conf/cmi/field.storage.paragraph.field_banner_text_align.yml, conf/cmi/language/fi/block.block.footernavigation.yml, conf/cmi/language/fi/block.block.languageswitcher.yml, conf/cmi/language/fi/block.block.menu_desktop.yml, conf/cmi/language/fi/block.block.menu_mobile.yml, conf/cmi/language/fi/block.block.menu_sidebar.yml, conf/cmi/language/fi/field.field.paragraph.banner_cta.field_banner_background_image.yml, conf/cmi/language/fi/field.field.paragraph.banner_cta.field_banner_link.yml, conf/cmi/language/fi/field.field.paragraph.banner_cta.field_banner_text_align.yml, conf/cmi/language/fi/field.field.paragraph.banner_cta.field_banner_title.yml, conf/cmi/language/fi/field.storage.paragraph.field_banner_text_align.yml, conf/cmi/language/fi/system.menu.footer-navigation.yml, conf/cmi/language/fi/system.menu.main.yml, public/themes/custom/suomidigi/src/scss/components/content/_article-teaser.scss, public/themes/custom/suomidigi/src/scss/components/content/_core-content-teaser.scss, public/themes/custom/suomidigi/src/scss/components/content/_core-content.scss, public/themes/custom/suomidigi/src/scss/components/paragraph/_paragraph--banner.scss, public/themes/custom/suomidigi/suomidigi.theme, public/themes/custom/suomidigi/templates/blocks/block--system-branding-block.html.twig, public/themes/custom/suomidigi/templates/content/community.html.twig, public/themes/custom/suomidigi/templates/content/node--article--teaser.html.twig, public/themes/custom/suomidigi/templates/content/node--core-content--teaser.html.twig, public/themes/custom/suomidigi/templates/content/node--legislation-collection-page--teaser.html.twig, public/themes/custom/suomidigi/templates/paragraph/paragraph--banner-cta.html.twig
To test: 
- `make fresh`
- Log in to your local environment, flush caches and add/edit some landing page
- Create new paragraph **Banner - CTA**
- Fill in the text and link fields and choose Left for text alignmnent (Or Tekstin tasaus: Teksti tasattu vasemmalle)
- Save the node and see that the banner looks like in the proto
- Mobile: https://ixonos.invisionapp.com/d/main#/console/16857736/349806795/preview
- Desktop: https://ixonos.invisionapp.com/d/main#/console/16859411/349551748/preview
=> SUOPA-476 Banner CTA

composer.lock, conf/cmi/core.entity_form_display.media.attachment.default.yml, conf/cmi/core.entity_form_display.media.attachment_external.default.yml, conf/cmi/core.entity_form_display.node.article.default.yml, conf/cmi/core.entity_form_display.node.core_content.default.yml, conf/cmi/core.entity_form_display.node.legislation_collection_page.default.yml, conf/cmi/core.entity_form_display.paragraph.attachment.default.yml, conf/cmi/core.entity_form_display.paragraph.banner_cta.default.yml, conf/cmi/core.entity_form_display.paragraph.liftup_box_item.default.yml, conf/cmi/core.entity_form_display.paragraph.media.default.yml, conf/cmi/core.entity_form_display.taxonomy_term.theme.default.yml, conf/cmi/field.field.node.legislation_collection_page.field_legis_cpage_paragraphs.yml, conf/cmi/field.field.taxonomy_term.theme.field_before_content_paragraphs.yml, conf/cmi/field.field.taxonomy_term.theme.field_liftup_image.yml, conf/cmi/field.field.taxonomy_term.theme.field_paragraphs.yml, public/modules/custom/suopa_dream_broker/assets/js/handleDreamBrokerTitle.js, public/modules/custom/suopa_editorial/assets/js/plugin.js, public/modules/custom/suopa_editorial/suopa_editorial.module
To test: 
- `make fresh`
- Go to any article and edit it
- Remove the main lift up image and check that this won't happen: https://monosnap.com/file/VHFykfM4EHabN6sXfimV8kqBjDOAyt
=> SUOPA-592 Entity reference replace button (Bug fix)

conf/cmi/core.entity_form_display.node.core_content.default.yml, conf/cmi/core.entity_view_display.node.core_content.default.yml, conf/cmi/field.field.node.core_content.field_tags.yml, conf/cmi/language/fi/field.field.node.core_content.field_tags.yml, conf/cmi/user.role.authenticated.yml, conf/cmi/user.role.content_producer.yml
To test:
- `make fresh`
- Log in and go to create an article https://suomidigi.docker.sh/node/add/article
- Add new Tags / Avainsana by typing and clicking the blue word with mouse or hitting enter/return key
- After saving the article, check that the Tags have been added to the taxonomy https://suomidigi.docker.sh/admin/structure/taxonomy/manage/tags/overview
=> SUOPA-301 Taxonomy terms

conf/cmi/block.block.menu_sidebar.yml, conf/cmi/field.field.paragraph.view.field_p_view.yml, conf/cmi/field.field.taxonomy_term.author.field_author_description.yml, conf/cmi/field.field.taxonomy_term.author.field_author_organisation.yml, conf/cmi/field.field.taxonomy_term.author.field_author_title.yml, conf/cmi/language.content_settings.taxonomy_term.author.yml, conf/cmi/language/fi/views.view.blogs.yml, conf/cmi/pathauto.pattern.blog_post_en.yml, conf/cmi/pathauto.pattern.blog_post_sv.yml, conf/cmi/views.view.blogs.yml
Changes from beta, exported via drush cex to dev.
=> Changes from beta, exported via drush cex to dev.

composer.json, composer.lock, conf/cmi/block.block.suomidigi_breadcrumbs.yml, conf/cmi/block.block.suomidigi_page_title.yml, conf/cmi/core.extension.yml, conf/cmi/easy_breadcrumb.settings.yml, conf/cmi/language/fi/easy_breadcrumb.settings.yml, conf/cmi/language/fi/webform.settings.yml, conf/cmi/language/sv/easy_breadcrumb.settings.yml, conf/cmi/language/sv/tour.tour.search-api-index.yml, conf/cmi/language/sv/tour.tour.search-api-server.yml, conf/cmi/language/sv/views.view.content.yml, conf/cmi/language/sv/views.view.files.yml, conf/cmi/language/sv/views.view.group_nodes.yml, conf/cmi/language/sv/views.view.media.yml, conf/cmi/language/sv/views.view.scheduler_scheduled_content.yml, conf/cmi/language/sv/views.view.user_admin_people.yml, public/themes/custom/suomidigi/src/scss/components/block/_local-tasks.scss, public/themes/custom/suomidigi/src/scss/components/content/_group.scss, public/themes/custom/suomidigi/src/scss/components/content/_landing-page.scss, public/themes/custom/suomidigi/src/scss/components/content/_page-title.scss, public/themes/custom/suomidigi/src/scss/components/navigation/_breadcrumb.scss, public/themes/custom/suomidigi/src/scss/components/paragraph/_paragraph.scss, public/themes/custom/suomidigi/src/scss/layout/_page.scss, public/themes/custom/suomidigi/suomidigi.theme, public/themes/custom/suomidigi/templates/layout/page.html.twig, public/themes/custom/suomidigi/templates/navigation/breadcrumb.html.twig
- To test: 
- Explore the site in desktop and mobile and check that the breadcrumbs work and look okay
- **Note**. The front page should not have breadcrumb.
=> SUOPA-772 Breadcrumb

conf/cmi/core.entity_form_display.paragraph.liftup_50_50.default.yml, conf/cmi/core.entity_view_display.paragraph.liftup_50_50.default.yml, conf/cmi/field.field.paragraph.liftup_50_50.field_p_button_cta.yml, conf/cmi/field.field.paragraph.liftup_50_50.field_p_separate.yml, conf/cmi/field.storage.paragraph.field_p_button_cta.yml, conf/cmi/field.storage.paragraph.field_p_separate.yml, conf/cmi/language/fi/field.field.paragraph.liftup_50_50.field_p_reverse.yml, conf/cmi/language/fi/field.field.paragraph.liftup_50_50.field_p_separate.yml, conf/cmi/views.view.articles.yml, public/modules/custom/suopa_editorial/suopa_editorial.module, public/themes/custom/suomidigi/src/scss/components/content/_event.scss, public/themes/custom/suomidigi/src/scss/components/content/_landing-page.scss, public/themes/custom/suomidigi/src/scss/components/misc/_button.scss, public/themes/custom/suomidigi/src/scss/components/misc/_link.scss, public/themes/custom/suomidigi/src/scss/components/paragraph/_paragraph--liftup-50-50.scss, public/themes/custom/suomidigi/src/scss/components/paragraph/_paragraph.scss, public/themes/custom/suomidigi/src/scss/library/variables/_colors.scss, public/themes/custom/suomidigi/templates/content/node--community.html.twig, public/themes/custom/suomidigi/templates/content/node--event--full.html.twig, public/themes/custom/suomidigi/templates/field/field--field-list-of-links-link.html.twig, public/themes/custom/suomidigi/templates/field/field--paragraph--field-p-button-cta.html.twig, public/themes/custom/suomidigi/templates/group/group--teaser-grid.html.twig, public/themes/custom/suomidigi/templates/group/group--teaser.html.twig, public/themes/custom/suomidigi/templates/misc/link.twig, public/themes/custom/suomidigi/templates/paragraph/paragraph--liftup-50-50.html.twig, public/themes/custom/suomidigi/templates/paragraph/paragraph--liftup-entity-reference.html.twig
To test: 
- Open proto page to a new tab: https://xd.adobe.com/view/d3c60a1d-1d76-4a8b-4797-030e9c2e717f-a5f7/screen/9c11d77d-86f9-4f29-9997-ddc12c3d0df1/Suomidigi-2020-osioetusivu-XL
- Log in and go to create landing page. https://suomidigi.docker.sh/node/add/landing_page
- Give the page a title and try make the page look like the one in the proto. There's a supportive video in slack.
- Also check that the paragraphs work on mobile. Mobile proto: https://xd.adobe.com/view/1067743e-f959-428d-664c-974d183bc243-6656/screen/6ebc7d4f-589d-4531-a8b9-ed6167f8c58b/Suomidigi-etusivu-mobile-1
=> SUOPA-783 Liftup 50/50

public/themes/custom/suomidigi/src/js/parallaxBackground.js, public/themes/custom/suomidigi/src/scss/components/navigation/_breadcrumb.scss, public/themes/custom/suomidigi/src/scss/components/views/_views--articles.scss, public/themes/custom/suomidigi/src/scss/layout/_page.scss, public/themes/custom/suomidigi/templates/layout/page.html.twig
To test: 
- `make fresh`
- Open proto: https://xd.adobe.com/view/d3c60a1d-1d76-4a8b-4797-030e9c2e717f-a5f7/screen/6b4e510f-7530-4c65-a60a-7d6001a34eab/Suomidigi-2020-artikkelit-XL
- Log in and go to edit a theme tag term of your choice. https://suomidigi.docker.sh/admin/structure/taxonomy/manage/theme/overview
- Add description for the theme tag term and save the term. 
- Go to https://suomidigi.docker.sh/kehittamisesimerkit and filter the view per the theme tag you've just edited. Check that the layout is similar to proto.
=> SUOPA-839 Theme tag description

conf/cmi/core.entity_form_display.group.group.default.yml, conf/cmi/core.entity_view_display.group.group.default.yml, conf/cmi/field.field.group.group.field_group_link_cta.yml, conf/cmi/field.storage.group.field_group_link_cta.yml, conf/cmi/pathauto.pattern.group_fi.yml, public/themes/custom/suomidigi/src/scss/components/block/_local-tasks.scss, public/themes/custom/suomidigi/src/scss/components/content/_blog-teaser.scss, public/themes/custom/suomidigi/src/scss/components/content/_group-teaser.scss, public/themes/custom/suomidigi/src/scss/components/content/_group.scss, public/themes/custom/suomidigi/src/scss/components/content/_landing-page.scss, public/themes/custom/suomidigi/src/scss/components/navigation/_breadcrumb.scss, public/themes/custom/suomidigi/src/scss/components/paragraph/_paragraph--group-views.scss, public/themes/custom/suomidigi/src/scss/components/paragraph/_paragraph.scss, public/themes/custom/suomidigi/src/scss/components/profile/_profile-card.scss, public/themes/custom/suomidigi/src/scss/layout/_page-before-content.scss, public/themes/custom/suomidigi/suomidigi.theme, public/themes/custom/suomidigi/templates/group/group--full.html.twig, public/themes/custom/suomidigi/templates/group/group--teaser.html.twig, public/themes/custom/suomidigi/templates/layout/page--group.html.twig, public/themes/custom/suomidigi/templates/layout/page--landing-page.html.twig, public/themes/custom/suomidigi/templates/layout/page.html.twig, public/themes/custom/suomidigi/templates/layout/region--before-content.html.twig, public/themes/custom/suomidigi/templates/views/views-view-unformatted--groups--groups.html.twig
To test: 
- `make fresh`
- Open proto https://xd.adobe.com/view/d3c60a1d-1d76-4a8b-4797-030e9c2e717f-a5f7/screen/a42df86c-6774-4be2-9202-6b18e64a7694/Suomidigi-2020-ryhma-XL
- Go to: https://suomidigi.docker.sh/ryhmat/digituki and check that the layout is similar to proto
- Also check that the mobile layout looks ok.
=> SUOPA-844 Group page

conf/cmi/context.context.sidebar.yml, public/modules/custom/suopa_content/suopa_content.install, public/modules/custom/suopa_editorial/src/Plugin/Block/ContentCreationLinksBlock.php, public/themes/custom/suomidigi/src/scss/components/content/_event.scss, public/themes/custom/suomidigi/src/scss/components/form/_form.scss, public/themes/custom/suomidigi/src/scss/layout/_page.scss, public/themes/custom/suomidigi/templates/content/node--event--full.html.twig, public/themes/custom/suomidigi/templates/field/contact-information.html.twig, public/themes/custom/suomidigi/templates/layout/page--node--add--event.html.twig
To test: 
- `make fresh`
- Go to https://suomidigi.docker.sh/tapahtumat
- Click on "Suomidigin lanseeraustilaisuus" and compare it to: https://xd.adobe.com/view/d3c60a1d-1d76-4a8b-4797-030e9c2e717f-a5f7/screen/ca9b6cdc-c018-4bff-afc7-11d3ca6baebf/Suomidigi-2020-suomidigi-tapahtuma
- Go back to https://suomidigi.docker.sh/tapahtumat
- Click on "Suomidigin työpaja" and compare it to: https://xd.adobe.com/view/d3c60a1d-1d76-4a8b-4797-030e9c2e717f-a5f7/screen/855b9152-a0d7-4bb7-b482-cef7a69ff591/Suomidigi-2020-minitapahtuma-1
- Log in as a user which has no roles and go to https://suomidigi.docker.sh/node/add/event and compare it to https://xd.adobe.com/view/d3c60a1d-1d76-4a8b-4797-030e9c2e717f-a5f7/screen/f2181903-7daf-4eab-b7f6-1f4ac58ba09e/Suomidigi-2020-luo-tapahtuma-XL
=> SUOPA-845 Event theme

conf/cmi/image.style.1_1_full_content.yml, conf/cmi/image.style.1_1_half_content.yml, conf/cmi/image.style.1_1_hd.yml, public/themes/custom/suomidigi/src/scss/components/paragraph/_paragraph--hero.scss, public/themes/custom/suomidigi/suomidigi.theme, public/themes/custom/suomidigi/templates/content/node--landing-page--full.html.twig, public/themes/custom/suomidigi/templates/paragraph/paragraph--hero.html.twig
To test: 
- `make fresh`
- Log in and go to https://suomidigi.docker.sh/node/7/edit 
- Copy the Hero texts from proto https://xd.adobe.com/view/d3c60a1d-1d76-4a8b-4797-030e9c2e717f-a5f7/
- Save the node
- Clear caches if the styles haven't been updated and compare the hero to proto. Also check mobile: https://xd.adobe.com/view/1067743e-f959-428d-664c-974d183bc243-6656/
=> SUOPA-798 Front page hero

conf/cmi/core.entity_form_display.media.attachment.default.yml, conf/cmi/core.entity_form_display.media.attachment_external.default.yml, conf/cmi/core.entity_form_display.paragraph.banner_cta.default.yml, conf/cmi/core.entity_view_display.paragraph.banner_cta.default.yml, conf/cmi/field.field.paragraph.banner_cta.field_p_description.yml, public/themes/custom/suomidigi/src/scss/components/content/_article-teaser.scss, public/themes/custom/suomidigi/src/scss/components/content/_attachment.scss, public/themes/custom/suomidigi/src/scss/components/form/_form.scss, public/themes/custom/suomidigi/src/scss/components/paragraph/_paragraph--attachment.scss, public/themes/custom/suomidigi/src/scss/components/paragraph/_paragraph--banner.scss, public/themes/custom/suomidigi/src/scss/components/paragraph/_paragraph--bullet-point.scss, public/themes/custom/suomidigi/src/scss/components/paragraph/_paragraph--cta.scss, public/themes/custom/suomidigi/src/scss/components/paragraph/_paragraph--text-box.scss, public/themes/custom/suomidigi/templates/content/media--attachment.html.twig, public/themes/custom/suomidigi/templates/paragraph/paragraph--attachment.html.twig, public/themes/custom/suomidigi/templates/paragraph/paragraph--banner-cta.html.twig, public/themes/custom/suomidigi/templates/paragraph/paragraph--highlight-cta.html.twig
To test: 
- `make fresh`
- Open proto: https://xd.adobe.com/view/d3c60a1d-1d76-4a8b-4797-030e9c2e717f-a5f7/screen/8cd19440-9868-4d6b-9be4-3f9d48e21023/Suomidigi-2020-palvelu-XL
- Go to https://suomidigi.docker.sh/palvelut/suomifi-tunnistus and look for **Lisätietoa 
käyttöönotosta**, compare it to protos **Palvelun tekninen kuvaus**
- On same page look for **Digitaalisen asioinnin tukipalvelukokonaisuus Suomi.fi,** compare it to protos **Digitaalisen asioinnin tukipalvelukokonaisuus Suomi.fi**
- Go to https://suomidigi.docker.sh/blogit/sarjakuvasta-tussivideoon-voisiko-lainsaadannosta-viestia-paremmin and look for attachments and compare them to protos **Lataa vaikuttavuusarviointipohja**
- Also check the attachment on page https://suomidigi.docker.sh/digituen-eettinen-ohjeistus
- Go to …
=> SUOPA-784 Paragraphs

composer.json, composer.lock, conf/cmi/pathauto.pattern.basic_page.yml, conf/cmi/pathauto.pattern.blog_post_en.yml, conf/cmi/pathauto.pattern.blog_post_fi.yml, conf/cmi/pathauto.pattern.blog_post_sv.yml, conf/cmi/pathauto.pattern.community_fi.yml, conf/cmi/pathauto.pattern.core_content.yml, conf/cmi/pathauto.pattern.event_en.yml, conf/cmi/pathauto.pattern.event_fi.yml, conf/cmi/pathauto.pattern.event_sv.yml, conf/cmi/pathauto.pattern.group_content.yml, conf/cmi/pathauto.pattern.group_content_path.yml, conf/cmi/pathauto.pattern.group_en.yml, conf/cmi/pathauto.pattern.group_fi.yml, conf/cmi/pathauto.pattern.group_sv.yml, conf/cmi/pathauto.pattern.landing_page.yml, conf/cmi/pathauto.pattern.news_item_en.yml, conf/cmi/pathauto.pattern.news_item_fi.yml, conf/cmi/pathauto.pattern.news_item_sv.yml, conf/cmi/pathauto.pattern.page.yml, conf/cmi/pathauto.pattern.theme_taxonomy.yml, conf/cmi/views.view.group_members.yml, public/modules/custom/suopa_tokens/suopa_tokens.module, public/themes/custom/suomidigi/src/scss/components/block/_auth-links.scss
To test: 
- `make fresh`
- Check that groups still work as expected and that the group content gets correct path aliases if saved with "Generate automatic URL alias" checked. Experiment f.e. with this node: https://suomidigi.docker.sh/node/429/edit
=> SUOPA-X Group content paths

composer.json
This is to fix problems with development version of paragraphs.
=> Composer is to override local changes.

composer.json, composer.lock
Test:
make drush-cr
make fresh
=> Update Drush to 10.2

conf/cmi/core.entity_view_display.group.group.search_index.yml, conf/cmi/core.entity_view_display.node.article.search_index.yml, conf/cmi/core.entity_view_display.node.blog_post.default.yml, conf/cmi/core.entity_view_display.node.blog_post.search_index.yml, conf/cmi/core.entity_view_display.node.community.search_index.yml, conf/cmi/core.entity_view_display.node.core_content.default.yml, conf/cmi/core.entity_view_display.node.core_content.search_index.yml, conf/cmi/core.entity_view_display.node.event.default.yml, conf/cmi/core.entity_view_display.node.event.search_index.yml, conf/cmi/core.entity_view_display.node.landing_page.default.yml, conf/cmi/core.entity_view_display.node.landing_page.search_index.yml, conf/cmi/core.entity_view_display.node.legislation_card.search_index.yml, conf/cmi/core.entity_view_display.node.legislation_collection_page.default.yml, conf/cmi/core.entity_view_display.node.legislation_collection_page.search_index.yml, conf/cmi/core.entity_view_display.node.news_item.search_index.yml, conf/cmi/core.entity_view_display.node.page.search_index.yml, conf/cmi/core.entity_view_mode.group.search_index.yml, conf/cmi/search_api.index.content_search_index.yml, conf/cmi/views.view.search.yml, public/themes/custom/suomidigi/src/scss/components/content/_community-teaser.scss, public/themes/custom/suomidigi/src/scss/components/navigation/_pager.scss, public/themes/custom/suomidigi/src/scss/components/navigation/_search-result.scss, public/themes/custom/suomidigi/suomidigi.theme, public/themes/custom/suomidigi/templates/content/node--community--search-index.html.twig, public/themes/custom/suomidigi/templates/content/node--search-index.html.twig, public/themes/custom/suomidigi/templates/views/views-view--search.html.twig, public/themes/custom/suomidigi/templates/views/views-view-unformatted--search.html.twig
To test: 
- `make fresh`
- Log in and go to https://suomidigi.docker.sh/admin/config/search/search-api/index/content_search_index
- Clear all indexed data and re-index the data
- Go through all of these links and make sure the search results have inherited the search results layout:
- Kehittämisesimerkki: https://suomidigi.docker.sh/haku?query=Digitaaliset
- Sivu: https://suomidigi.docker.sh/haku?query=Digimentorit
- Blogikirjoitus: https://suomidigi.docker.sh/haku?query=Digituen+verkosto+rakentuu
- Verkosto: https://suomidigi.docker.sh/haku?query=Digitukijat
- Ydinsisältö: https://suomidigi.docker.sh/haku?query=Suomi.fi-viestit
- Tapahtumat: https://suomidigi.docker.sh/haku?query=Suomidigin+lanseeraus
- Ländäri: https://suomidigi.docker.sh/haku?query=Tapahtumat (Found from the bottom of …
=> SUOPA-858 Search content

Dockerfile
Configuration change for AWS-environment
=> Create symlink to public files.

Dockerfile
Configuration change for AWS-environment
=> Create symlink for private files.

conf/cmi/core.extension.yml, public/modules/custom/suopa_user/src/EventSubscriber/SocialAuthSubscriber.php, public/modules/custom/suopa_user/suopa_user.info.yml, public/modules/custom/suopa_user/suopa_user.services.yml
Hotfix for user real name and user - author reference when creating user from social media auth
=> Dev -> Beta 9.3.2020 (hotfix)

conf/cmi/core.entity_form_display.media.attachment.default.yml, conf/cmi/core.entity_form_display.media.attachment.media_library.yml, conf/cmi/core.entity_form_display.media.attachment_external.default.yml, conf/cmi/core.entity_form_display.media.attachment_external.media_library.yml, conf/cmi/core.entity_form_display.node.article.default.yml, conf/cmi/core.entity_form_display.node.blog_post.default.yml, conf/cmi/core.entity_form_display.node.core_content.default.yml, conf/cmi/core.entity_form_display.node.news_item.default.yml, conf/cmi/core.entity_form_display.node.page.default.yml, conf/cmi/core.entity_form_display.paragraph.attachment.default.yml, conf/cmi/core.entity_view_display.media.attachment.default.yml, conf/cmi/core.entity_view_display.media.attachment.media_library.yml, conf/cmi/core.entity_view_display.media.attachment.media_paragraph.yml, conf/cmi/core.entity_view_display.media.attachment_external.default.yml, conf/cmi/core.entity_view_display.media.attachment_external.media_library.yml, conf/cmi/core.entity_view_display.media.attachment_external.media_paragraph.yml, conf/cmi/core.entity_view_display.node.blog_post.default.yml, conf/cmi/field.field.media.attachment.field_accessibility_required.yml, conf/cmi/field.field.media.attachment_external.field_accessibility_required.yml, conf/cmi/field.storage.media.field_accessibility_required.yml, conf/cmi/language/fi/field.field.media.attachment.field_accessibility_required.yml, conf/cmi/language/fi/field.field.media.attachment_external.field_accessibility_required.yml, conf/cmi/language/fi/views.view.media_library.yml, conf/cmi/language/fi/views.view.moderated_content.yml, conf/cmi/language/sv/system.menu.admin.yml, public/modules/custom/suopa_editorial/assets/css/media_entity_browser.css, public/modules/custom/suopa_editorial/suopa_editorial.module
To test: 
- Log in and go to create landing-page: https://suomidigi.docker.sh/node/add/landing_page
- Add new paragraph "Liitteet" and click on "Valitse liite"
- Click on "Lisää uusi liite" and try to create an attachment without checking the checkbox
- Click on "Lisää uusi ulkoinen liite" and try to create an external attachment without checking the checkbox
- Go to https://suomidigi.docker.sh/media/add/attachment and https://suomidigi.docker.sh/media/add/attachment_external and try create attachments without checking the checkbox
=> SUOPA-923 Accessibility confirmation

composer.json, composer.lock, conf/cmi/core.entity_view_display.media.image.media_paragraph.yml, conf/cmi/core.extension.yml, conf/cmi/language/fi/views.view.taxonomy_term.yml, conf/cmi/language/sv/views.view.taxonomy_term.yml, public/themes/custom/suomidigi/src/scss/components/misc/_button.scss
To test: 
- Go to f.e. https://suomidigi.docker.sh/node/434 and try to click the media paragraph image (the one in the middle of the content) and see if it opens in a popup
=> SUOPA-906 Media paragraph popup

public/modules/custom/suopa_group/suopa_group.module
Allow group admin to publish their own content.
=> SUOPA-X Hotfix group admin

conf/cmi/core.entity_form_display.node.blog_post.default.yml, conf/cmi/field.field.node.blog_post.field_blog.yml, conf/cmi/language/fi/field.field.node.blog_post.field_blog.yml, conf/cmi/nodeorder.settings.yml, conf/cmi/pathauto.pattern.blog_taxonomy_en.yml, conf/cmi/pathauto.pattern.blog_taxonomy_fi.yml, conf/cmi/pathauto.pattern.blog_taxonomy_sv.yml, conf/cmi/rabbit_hole.behavior_settings.taxonomy_vocabulary_blog.yml, conf/cmi/tvi.taxonomy_vocabulary.blog.yml, conf/cmi/views.view.blogs.yml
To test: 
- `make fresh`
- Log in and flush all the caches form the UI to apply changes for taxonomy term views. 
- Go to https://suomidigi.docker.sh/admin/structure/taxonomy/manage/blog/overview
- Add a new term for your custom blog series and once saved, open the taxonomy term page on new browser tab. 
- Go to https://suomidigi.docker.sh/admin/content?type=blog_post
- Edit few of the blog posts and apply the blog series what you've just created
- Go to the browser tab where the new blog series term is open and refresh the page. 
- Make sure the blog posts have appeared to the list.
=> SUOPA-927 Blog categories

conf/cmi/context.context.related_content.yml, conf/cmi/language/fi/views.view.related_content.yml, conf/cmi/views.view.related_content.yml, public/themes/custom/suomidigi/src/scss/components/navigation/_menu-mobile.scss, public/themes/custom/suomidigi/src/scss/layout/_page.scss, public/themes/custom/suomidigi/suomidigi.theme, public/themes/custom/suomidigi/templates/views/views-view-unformatted--related-content.html.twig
To test: 
- Go to https://suomidigi.docker.sh/kehittamisesimerkit or https://suomidigi.docker.sh/blogit and open few nodes to a new tab
- Check that there is a related content view (You may be interested) in the bottom of the node. The order of related content is randomised
=> SUOPA-926 Related content

.env, Makefile, composer.json, composer.lock, drush/Commands/CacheClearCommands.php, drush/amazeeio.aliases.drushrc.php, public/modules/custom/suopa_editorial/suopa_editorial.install, tools/make/Makefile, tools/make/amazeeio.mk, tools/make/common.mk, tools/make/composer.mk, tools/make/docker.mk, tools/make/drupal.mk, tools/make/javascript.mk, tools/make/project/kube-sync.mk, tools/make/project/robots.mk, tools/make/project/stagefileproxy.mk, tools/make/qa.mk, tools/make/utils.mk
Enabling file stage proxy for other that production environments.
Test: make fresh; make drush-cr;
You should not see files sync at all. After uli you will get file_stage_proxy enabled.
Delete files from public/sites/default/files
Browse the site and make sure images load and attachment can be downloaded.
=> Enabling file stage proxy

conf/cmi/field.field.node.article.field_paragraphs.yml, conf/cmi/field.field.node.blog_post.field_paragraphs.yml, conf/cmi/field.field.node.core_content.field_paragraphs.yml, conf/cmi/field.field.node.landing_page.field_paragraphs.yml, conf/cmi/field.field.node.legislation_card.field_attachments.yml, conf/cmi/field.field.node.legislation_card.field_legislation_materials.yml, conf/cmi/field.field.node.legislation_collection_page.field_legis_cpage_paragraphs.yml, conf/cmi/field.field.node.news_item.field_paragraphs.yml, conf/cmi/field.field.node.page.field_paragraphs.yml
To test: 
- Check the documentation and code. https://wiki.dvv.fi/display/SUOPA/Suomidigi.fi+paragraafit
=> SUOPA-919 Paragraphs cleanup

tools/make/project/kube-sync.mk
make down
make fresh
check that database is synced from aws - files are not synced. 
site should work :)
=> Suopa 928 make fresh

conf/cmi/context.context.profle.yml, public/themes/custom/suomidigi/src/scss/components/content/_blog-teaser.scss, public/themes/custom/suomidigi/src/scss/components/content/_event-teaser.scss, public/themes/custom/suomidigi/src/scss/components/content/_moderation-state.scss, public/themes/custom/suomidigi/src/scss/library/variables/_colors.scss, public/themes/custom/suomidigi/suomidigi.theme, public/themes/custom/suomidigi/templates/content/node--blog-post--teaser.html.twig, public/themes/custom/suomidigi/templates/content/node--event--teaser.html.twig
To test: 
- `make fresh`
- Open proto to a new tab: https://xd.adobe.com/view/d3c60a1d-1d76-4a8b-4797-030e9c2e717f-a5f7/screen/c3d5bba7-d451-4367-b712-0d41e745ec3d/Suomidigi-2020-oma-profiili/
- Log in and go to your profile page https://suomidigi.docker.sh/user
- Create new blog post (remember to add your user as an author!)
- Save the blog post as a draft
- Go to your own page and check that the draft layout is similar to proto
- Edit the blog post and save it as "waiting for publication"
- Go to your own page and check that the draft layout is similar to proto
- Repeat this with event content type
=> SUOPA-922 Content statutes

composer.json, composer.lock, conf/cmi/core.extension.yml, conf/cmi/xmlsitemap.settings.group.group.yml, conf/cmi/xmlsitemap.settings.node.article.yml, conf/cmi/xmlsitemap.settings.node.blog_post.yml, conf/cmi/xmlsitemap.settings.node.community.yml, conf/cmi/xmlsitemap.settings.node.core_content.yml, conf/cmi/xmlsitemap.settings.node.event.yml, conf/cmi/xmlsitemap.settings.node.landing_page.yml, conf/cmi/xmlsitemap.settings.node.legislation_card.yml, conf/cmi/xmlsitemap.settings.node.legislation_collection_page.yml, conf/cmi/xmlsitemap.settings.node.news_item.yml, conf/cmi/xmlsitemap.settings.node.page.yml, conf/cmi/xmlsitemap.settings.node.webform.yml, conf/cmi/xmlsitemap.settings.yml, conf/cmi/xmlsitemap.xmlsitemap.PYgq5vYzAuvYMcuKajN7voJEvUlYuPXv7goZjmMJ8Fk.yml
This PR installs and enables XML-Sitemap and Initial configuration for Google indexing to succeed.
Testing:
Goto build sitemap:
https://suomidigi.docker.sh/admin/config/search/xmlsitemap/rebuild
Check that sitemap is generated:
https://suomidigi.docker.sh/sitemap.xml
=> Enable XML-Sitemap and Initial configuration

composer.json, composer.lock, conf/cmi/search_api.index.content_search_index.yml
Updated Drupal core from 8.8.6 to 8.8.8
=> Dev -> Beta

Dockerfile, public/sites/default/settings.php
Added /public/libraries & /public/core to Git (need to exist for deployment)
Changed aws domains in dvv-format
=> AWS Deployment issue with new domain and cluster

Dockerfile, conf/cmi/key.config_override.smtp_address.yml, conf/cmi/key.config_override.smtp_port.yml, conf/cmi/key.key.smtp_address.yml, conf/cmi/key.key.smtp_password.yml, conf/cmi/key.key.smtp_port.yml, conf/cmi/key.key.smtp_user.yml, conf/cmi/swiftmailer.transport.yml, public/sites/default/dev.settings.php, public/sites/default/prod.settings.php
AWS SMTP configuration settings via key module
=> Suopa 871 aws smtp config

composer.json, composer.lock, public/themes/custom/suomidigi/src/scss/components/form/_form.scss
Webform 5.20 added some excess divs with class js-form-wrappers and this broke UI in some places.
Updated Webform to 5.21 which fixes this issue. https://www.drupal.org/project/webform/issues/3172874
Also removed some excess margin from checkboxes
Testing guide:
Goto: https://docker.suomidigi.fi/palaute
Yhteystiedot - header should be on its own line and rest of the form items in 2 columns
Not like this:
But like this:
Also this whitespace should be gone:
=> Fix layout issues with latest webform update

README.md
- This fixes Media Browser related JS issue, that blocks using mediabrowser.
- Update to Readme
=> Deployment 2.10.2020: Fix media browser

composer.lock
=> Drupal security update 8.9.16

composer.json, composer.lock
Fixes CKeditor issue: https://www.drupal.org/sa-core-2021-003
=> Security Update Drupal Core 8.9.16
